defaults:
  - generators:
      #    - vague
      #    - scope
      #    - attachment
      #      - col_unans
      - calc_unans
db_path: 'fake_db_with_joins.sqlite'
db_id: null
only_these_tbl: null