from squab.nodes.test_generation.node_templates_attach import create_templates_attach
from squab.nodes.test_generation.node_templates_col_unans import create_templates_col_unans
from squab.nodes.test_generation.node_templates_scope import create_templates_scope
from squab.nodes.test_generation.node_templates_udf_unans import create_templates_udf_unans
from squab.nodes.test_generation.node_templates_vague import create_templates_vague
